name = "Custom Server Modpack"
author = "vik/"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07ca63bfb42e9acde6da3c6db06e2a5a48a4f7aeca9b68d0899af9863136987e"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
meta-folder = "mods"
