name = "Custom Server Modpack"
author = "vik/"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "910bd7326096b2ff568bf378955ba328072d0781e0e27de19484a61d4a6aded2"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
meta-folder = "mods"
