name = "Custom Server Modpack"
author = "vik/"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8db9593bb51c38351131a42b4808f598f8977fefc4f32e712c0a2dc69261ded1"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
datapack-folder = "datapacks"
meta-folder = "mods"
