name = "Custom Server Modpack"
author = "vik/"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f1f24148d431270c8dd357227bf59dace7c34d71300f6a05c7dcb16b1b95f5d"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
datapack-folder = "datapacks"
meta-folder = "mods"
