name = "Custom Server Modpack"
author = "vik/"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2da9a728761e5a0aad12bccc13e799281f651dada76f97e64d0b2f5615b989b6"

[versions]
fabric = "0.19.5"
minecraft = "26.2"

[options]
datapack-folder = "datapacks"
meta-folder = "mods"
